# FROM node:8.9.1-alpine

# COPY package.json yarn.lock /usr/src/
# RUN cd /usr/src \
#     && yarn install --pure-lockfile

# COPY . /usr/src
# ARG BUILD_CONTEXT
# pull the base image
# FROM node:19-bullseye as build

# WORKDIR /usr/src/app
# COPY package*.json ./
# COPY yarn.lock .
# rebuild node-sass
# RUN yarn add node-sass
# RUN npm i @parcel/transformer-sass
# RUN yarn install
# COPY ./ /app/
# copy . .
# expose 1234
# CMD [ "yarn", "parcel", "index.html" ]
# CMD [ "npm run", "build", 'src/index.html']
# run yarn build
# run npm run build
# run yarn dev
# CMD ['yarn' 'dev']

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
RUN rm -rf /etc/nginx/conf.d/*
RUN sed -i 's,notice,crit,g' /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY build /usr/share/nginx/html

# EXPOSE 1234
# CMD ["nginx", "-g", "daemon off;"]


